module.exports.bull = {
    redis: {
        host: 'localhost',
        port: 6379,
        db: 0,
        maxRetriesPerRequest: null,
        enableReadyCheck: false
    },
    //generate cron format using: https://crontab.guru
    repeats: [{
        name: 'clean_completed_jobs', // generated by business-stack-generator, job is used to clean completed tasks
        active: true,
        repeat: { cron: "0 1 * * *" },
        data: {}
    },
    {
        name: 'clean_failed_jobs', // generated by business-stack-generator, job is used to clean failed tasks
        active: true,
        repeat: { cron: "0 1 * * *" },
        data: {}
    }]
}